name: "Build and push Super Mario Docker image with dynamic tag to Docker Hub"

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow workflow to push changes back to repo

jobs:
  build_push_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Version
        id: version
        run: |
          VERSION=$(($(cat version.txt) + 1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/supermariogitopsproject
          docker build -t $IMAGE_NAME:${{ env.VERSION }} -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:${{ env.VERSION }}
          docker push $IMAGE_NAME:latest

      - name: Update version.txt
        run: |
          echo "${{ env.VERSION }}" > version.txt
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add version.txt
          git commit -m "Bump version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
